name: Build and push GEO to ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'src/geo-service/**'
      - '.github/workflows/build-and-push-geo.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: ecr-login

      - name: Build, tag, and push geo image
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          ECR_REPOSITORY: diia-parking-ctrl-geo
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REPOSITORY:latest ./src/geo-service/diia-parking-ctrl.geo-service/
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster diia-parking-ctrl-dev-cluster \
            --service geo-service \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}
